---
name: Pull Requests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    steps:
      - name: Set Maven Options
        run:
          echo "::set-env name=MAVEN_OPTS::-Dmaven.repo.local=$HOME/.m2/repository"
      - uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Run Tests
        run: mvn $MAVEN_CLI_OPTS install
